apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-context-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-context-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
